// This file was generated by lezer-generator. You probably shouldn't edit it.
export const JsonText = 1;
export const True = 2;
export const False = 3;
export const Null = 4;
export const Number = 5;
export const String = 6;
export const Object = 9;
export const Property = 10;
export const PropertyName = 11;
export const Array = 14;
export const EjsOutput = 15;
export const JavascriptExpression = 16;
