// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser, LocalTokenGroup } from '@lezer/lr';

export const parser = LRParser.deserialize({
  version: 14,
  states:
    "%jOVQPOOOOQO'#Cb'#CbOtQPO'#CeO!PQPO'#CjO!ZOQO'#CxOOQO'#Ck'#CkO!`OPO'#CkOOQO'#Cr'#CrQOQPOOOOQO'#Cg'#CgO!eQPO'#CfO!jQPO'#CmO!uQPO'#CtO!uQPO'#CtPOQO,59P,59PO!}QPO,59PO#SQPO'#CnO#^QPO'#CwO#^QPO'#CwPOQO,59U,59UO#fQPO,59UO#kOQO,59dO#pOPO,59VOVQPO,59QOOQO,59X,59XOOQO-E6k-E6kO#uQPO,59`OOQO1G.k1G.kOOQO,59Y,59YOOQO-E6l-E6lO#}QPO,59cOOQO1G.p1G.pOOQO1G/O1G/OOOQO1G.q1G.qOOQO1G.l1G.l",
  stateData:
    '$V~OeOS~OQVORVOSVOTVOWQO]ROgPOmSOoUO~OgXOjZOVhP~Oj`O[kP~PVO`eO~OmSO~OigO~OgXOVaXjaX~OjZOVhX~OVkO~O[bXjbX~PVOj`O[kX~O[oO~OnpO~OoqO~OjZOVha~Oj`O[ka~O',
  goto: '#PmPPPPPPnPPntzPPnnP!O!YPPP!dP!pPP!s!vXVOR`gQ]QRhZTYQZQ[QSi[jRj]QaRSmanRnbQWOQbRQl`RrgR_QRdRWTOR`gRfU',
  nodeNames:
    '⚠ JsonText True False Null Number String } { Object Property PropertyName ] [ Array EjsOutput JavascriptExpression',
  maxTerm: 31,
  nodeProps: [
    ['openedBy', 7, '{', 12, '['],
    ['closedBy', 8, '}', 13, ']'],
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData:
    "*P~RbXY!ZYZ!Z]^!Zpq!Zrs!`|}%g}!O%l!Q!R%u!R!['T![!]'f!^!_'k!}#O'|#P#Q(R#Y#Z(W#b#c(u#h#i)^#o#p)u#q#r)z~!`Oe~~!eWo~pq!}qr!}rs#js#O!}#O#P#o#P;'S!};'S;=`%a<%lO!}~#QWpq!}qr!}rs#js#O!}#O#P#o#P;'S!};'S;=`%a<%lO!}~#oOg~~#rXrs!}!P!Q!}#O#P!}#U#V!}#Y#Z!}#b#c!}#f#g!}#h#i!}#i#j$_~$bR!Q![$k!c!i$k#T#Z$k~$nR!Q![$w!c!i$w#T#Z$w~$zR!Q![%T!c!i%T#T#Z%T~%WR!Q![!}!c!i!}#T#Z!}~%dP;=`<%l!}~%lOj~~%oQ!Q!R%u!R!['T~%zRT~!O!P&T!g!h&i#X#Y&i~&WP!Q![&Z~&`RT~!Q![&Z!g!h&i#X#Y&i~&lR{|&u}!O&u!Q![&{~&xP!Q![&{~'QPT~!Q![&{~'YST~!O!P&T!Q!['T!g!h&i#X#Y&i~'kOi~~'nPuv'q~'tP!_!`'w~'|Om~~(RO]~~(WO[~~(ZP#T#U(^~(aP#`#a(d~(gP#g#h(j~(mP#X#Y(p~(uOR~~(xP#i#j({~)OP#`#a)R~)UP#`#a)X~)^OS~~)aP#f#g)d~)gP#i#j)j~)mP#X#Y)p~)uOQ~~)zOW~~*POV~",
  tokenizers: [1, new LocalTokenGroup('n~RPuvU~XR}!Ob!`!ah#R#Sb~eP!`!ah~mOn~~', 29, 16)],
  topRules: { JsonText: [0, 1] },
  tokenPrec: 0,
});
