version: '3.5'

services:
  mysql:
    image: mysql:8-debian
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_PORT: 3306
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - mysql
    command: start-dev

volumes:
  mysql_data: