global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus_master"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: 'nginx_status'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx:80']
