export const MENU_VALIDATION = {
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 30,
  META_NAME_MIN_LENGTH: 3,
  META_NAME_MAX_LENGTH: 30,
};

export const MENU_ITEM_VALIDATION = {
  LABEL_MIN_LENGTH: 3,
  LABEL_MAX_LENGTH: 30,
};

export const MENU_REVISION_VALIDATION = {
  DESCRIPTION_MIN_LENGTH: 3,
  DESCRIPTION_MAX_LENGTH: 255,
};
