name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify `--force` as a flag for git pushes
          branch: develop
          git_push_flags: '--force'
          git_remote_url: ${{ secrets.DOKKU_SSH_URL }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}